/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Investment } from "./Investment";
import { InvestmentCountArgs } from "./InvestmentCountArgs";
import { InvestmentFindManyArgs } from "./InvestmentFindManyArgs";
import { InvestmentFindUniqueArgs } from "./InvestmentFindUniqueArgs";
import { CreateInvestmentArgs } from "./CreateInvestmentArgs";
import { UpdateInvestmentArgs } from "./UpdateInvestmentArgs";
import { DeleteInvestmentArgs } from "./DeleteInvestmentArgs";
import { Scheme } from "../../scheme/base/Scheme";
import { User } from "../../user/base/User";
import { InvestmentService } from "../investment.service";
@graphql.Resolver(() => Investment)
export class InvestmentResolverBase {
  constructor(protected readonly service: InvestmentService) {}

  async _investmentsMeta(
    @graphql.Args() args: InvestmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Investment])
  async investments(
    @graphql.Args() args: InvestmentFindManyArgs
  ): Promise<Investment[]> {
    return this.service.investments(args);
  }

  @graphql.Query(() => Investment, { nullable: true })
  async investment(
    @graphql.Args() args: InvestmentFindUniqueArgs
  ): Promise<Investment | null> {
    const result = await this.service.investment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Investment)
  async createInvestment(
    @graphql.Args() args: CreateInvestmentArgs
  ): Promise<Investment> {
    return await this.service.createInvestment({
      ...args,
      data: {
        ...args.data,

        scheme: args.data.scheme
          ? {
              connect: args.data.scheme,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Investment)
  async updateInvestment(
    @graphql.Args() args: UpdateInvestmentArgs
  ): Promise<Investment | null> {
    try {
      return await this.service.updateInvestment({
        ...args,
        data: {
          ...args.data,

          scheme: args.data.scheme
            ? {
                connect: args.data.scheme,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Investment)
  async deleteInvestment(
    @graphql.Args() args: DeleteInvestmentArgs
  ): Promise<Investment | null> {
    try {
      return await this.service.deleteInvestment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Scheme, {
    nullable: true,
    name: "scheme",
  })
  async getScheme(
    @graphql.Parent() parent: Investment
  ): Promise<Scheme | null> {
    const result = await this.service.getScheme(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Investment): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
